#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if [ -d /run/systemd/system ]; then
        systemctl stop mq-sentinel.service || true
        systemctl disable mq-sentinel.service || true
    fi
fi

#DEBHELPER#
exit 0
